### ISSUE TITLE
[Fix]#17 - solving dev branch conflict

### ISSUE THREAD

**Issue by cantabilano** [Weather-777/weather777#17]
## To-do

- [x] 라이브러리 관련 Pod 이력 삭제
- [x] Link Binary With Libraries 항목 추가 
- [x] Gifu 버전 3.4.1 임의 설정 후 설치
![스크린샷 2024-02-07 21 14 16](https://github.com/Weather-777/weather777/assets/88497383/e6305356-0a53-496d-bbfd-93549787b842)
