### ISSUE TITLE
[Fix]#22- 5일치 3시간 단위 날씨 데이터 API 적용

### ISSUE THREAD

**Issue by cantabilano** [Weather-777/weather777#22]
## To-do

- [x] 현재 날씨 API와 5일치 3시간 단위 날씨 데이터 API가 다름에 따라, 3시간 단위 날씨 데이터 API로  WeatherData 모델 변경
- [x] 5일치 3시간 단위 날씨 데이터 API를 적용한 getForecastWeather 매소드 추가 
- [x] URL extension으로 변경

**Comment by cantabilano** [comment]
695c26b에서 5일치3시간 단위 날씨예보를 참고하시면 되겠습니다.
