### ISSUE TITLE
[Feat]#24 - API로 호출한 데이터 배열화

### ISSUE THREAD

**Issue by cantabilano** [Weather-777/weather777#24]
## To-do

- [x] 현재온도, 최고온도, 최저온도, 날씨 아이콘, 위치정보 배열화
- [x] (추가) 섭씨, 화씨 extension
- [x] (추가) 습도, 최고온도, 최저온도, 체감온도, 강수량
