### ISSUE TITLE
[Fix]#29 - Map folder 경고창 수정

### ISSUE THREAD

**Issue by RACHEL056** [Weather-777/weather777#29]
## To-do

- [x] self 참조 경고
- [x] button edgeInset 경고
- [x] InfoModalVC weak var로 VC 참조 경고
