### ISSUE TITLE
[Feat]#3 - OpenWeatherMap Key 관련

### ISSUE THREAD

**Issue by cantabilano** [Weather-777/weather777#3]
## To-do

- [x] OpenWeatherMap API를 활용한 WeatherData 모델 만들기
- [x] 싱글톤 패턴으로 WeatherManager 생성(public func performRequest)
- [x] OpenWeatherMap API key를 URLSession으로 호출하기 
- [x] 보안을 위해 key 값 숨기기(WeatherKey)
- [x] 싱글톤 패턴으로 LocationManager 생성(public func requestLocation, locationManager, setLocation)

**Comment by cantabilano** [comment]
branch 번호 변경으로 인해 삭제 처리하겠습니다.
